### ISSUE TITLE
Final Submission of Final Project

### ISSUE THREAD

**Issue by maexuhaoyu** [qmss-gr5063-2019/Group_M_Economic_Comparison#2]
@tbrambor @eddiecylin @JiaxiYang1992 , 4925687

**Comment by tbrambor** [comment]
Comments for the Group:

There are substantial issues with the website implementation, choice of visualizations, usability, labeling etc. throughout most parts of the project. Many graphs provide insufficient labeling and no additional explanation to follow the story and patterns presented. Each tab seems to come from a different author (and just may) with no coherence in templating and user experience. The app is laggy and restricted to internet explorer users (for no good reason in functionality as far as I can tell). The googleVis motion chart is attractive but in terms of technical expertise and novelty very close to much of existing code available on the internet already. Overall, this project is underwhelming and has plenty of room to improve.

Overall Grade: B-
